directories:
  output: release/build
  buildResources: assets
  app: release/app
productName: DmClient-dev
appId: com.innodealing.DmClient
asar: true
asarUnpack: '**\*.{node,dll}'
files:
  - filter:
      - dist
      - node_modules
      - package.json
publish:
  - provider: generic
    url: ''
afterSign: .erb/scripts/notarize.js
mac:
  target:
    target: default
    arch:
      - arm64
      - x64
  type: distribution
  hardenedRuntime: true
  entitlements: assets/entitlements.mac.plist
  entitlementsInherit: assets/entitlements.mac.plist
  gatekeeperAssess: false
dmg:
  artifactName: ${productName}-${platform}-${version}.${ext}
  contents:
    - x: 130
      'y': 220
    - x: 410
      'y': 220
      type: link
      path: /Applications
win:
  target:
    target: nsis
    arch:
      - x64
      - ia32
nsis:
  oneClick: false
  language: '2052'
  perMachine: true
  allowToChangeInstallationDirectory: true
  artifactName: ${productName}-Setup-${arch}-${version}.${ext}
linux:
  target:
    - AppImage
  category: Development
  artifactName: ${productName}-${platform}-${arch}-${version}.${ext}
extraResources:
  - filter:
      - ./assets/**
electronVersion: 22.0.0
